In [1]:
print("hello")

hello

In [2]:
print("Mrudula")

Mrudula

In [3]:
print("The world nis beautiful")

The world nis beautiful

In [4]:
a=4
print("a")

a

In [5]:
b=7
print(int)

<class 'int'>

In [6]:
b=8
print("int")

int

In [ ]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [1]:
import pandas as pd

In [2]:
Customer Shopping Behavior Analysis = pd.read_csv(r"C:\Users\Admin\OneDrive\Documents\Mrudula\"Customer Shopping Behavior Analysis")

SyntaxError: invalid syntax (1079344496.py, line 1)

In [5]:
print("Mrusula")

Mrusula

In [6]:
pip install pandas openpyxl

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

df = pd.read_excel(r"C:\Users\Admin\OneDrive\Documents\Mrudula\Customer Shopping Behavior Analysis.xlsx")

df.head()

,Customer id,Age,Gender,item purchase,Category,Purchase amount,location,size,color,season,review rating,subcription status,ship[ping type,discount applied,Promo code used,Previous purchase,payment method,frequency 5of purchase
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 609 entries, 0 to 608
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer id             609 non-null    int64
 1   Age                     609 non-null    int64
 2   Gender                  609 non-null    str
 3   item purchase           609 non-null    str
 4   Category                609 non-null    str
 5   Purchase amount         609 non-null    int64
 6   location                609 non-null    str
 7   size                    609 non-null    str
 8   color                   609 non-null    str
 9   season                  609 non-null    str
 10  review rating           594 non-null    float64
 11  subcription status      609 non-null    str
 12  ship[ping type          609 non-null    str
 13  discount applied        609 non-null    str
 14   Promo code used        609 non-null    str
 15  Previous purchase       609 non-null    int64
 16  payment method          609 non-null    str
 17  frequency 5of purchase  609 non-null    str
dtypes: float64(1), int64(4), str(13)
memory usage: 85.8 KB

In [5]:
df.describe()

,Customer id,Age,Purchase amount,review rating,Previous purchase
count,609.000000,609.000000,609.000000,594.000000,609.000000
mean,305.000000,43.954023,59.753695,3.773401,26.231527
std,175.947435,15.182373,23.510463,0.715263,14.242516
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,153.000000,31.000000,39.000000,3.200000,14.000000
50%,305.000000,44.000000,60.000000,3.700000,26.000000
75%,457.000000,57.000000,81.000000,4.400000,39.000000
max,609.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.describe(include='all')

,Customer id,Age,Gender,item purchase,Category,Purchase amount,location,size,color,season,review rating,subcription status,ship[ping type,discount applied,Promo code used,Previous purchase,payment method,frequency 5of purchase
count,609.000000,609.000000,609,609,609,609.000000,609,609,609,609,594.000000,609,609,609,609,609.000000,609,609
unique,NaN,NaN,1,25,4,NaN,50,4,25,4,NaN,1,6,1,1,NaN,6,7
top,NaN,NaN,Male,Coat,Clothing,NaN,California,M,Olive,Fall,NaN,Yes,Store Pickup,Yes,Yes,NaN,Debit Card,Annually
freq,NaN,NaN,609,36,259,NaN,21,280,37,160,NaN,609,123,609,609,NaN,111,107
mean,305.000000,43.954023,NaN,NaN,NaN,59.753695,NaN,NaN,NaN,NaN,3.773401,NaN,NaN,NaN,NaN,26.231527,NaN,NaN
std,175.947435,15.182373,NaN,NaN,NaN,23.510463,NaN,NaN,NaN,NaN,0.715263,NaN,NaN,NaN,NaN,14.242516,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,153.000000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.200000,NaN,NaN,NaN,NaN,14.000000,NaN,NaN
50%,305.000000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,26.000000,NaN,NaN
75%,457.000000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,39.000000,NaN,NaN
max,609.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer id                0
Age                        0
Gender                     0
item purchase              0
Category                   0
Purchase amount            0
location                   0
size                       0
color                      0
season                     0
review rating             15
subcription status         0
ship[ping type             0
discount applied           0
 Promo code used           0
Previous purchase          0
payment method             0
frequency 5of purchase     0
dtype: int64

In [ ]:
df['review rating']=df.groupby('category')['review rating'].transform(lambda x:x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer id                0
Age                        0
Gender                     0
item purchase              0
Category                   0
Purchase amount            0
location                   0
size                       0
color                      0
season                     0
review rating             15
subcription status         0
ship[ping type             0
discount applied           0
 Promo code used           0
Previous purchase          0
payment method             0
frequency 5of purchase     0
dtype: int64

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.columns

Index(['customer_id', 'age_', 'gender', 'item_purchase', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subcription_status', 'ship[ping_type',
       'discount_applied', '_promo_code_used', 'previous_purchase',
       'payment_method', 'frequency_5of_purchase'],
      dtype='str')

In [17]:
print(df.columns.tolist())

['customer_id', 'age_', 'gender', 'item_purchase', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subcription_status', 'ship[ping_type', 'discount_applied', '_promo_code_used', 'previous_purchase', 'payment_method', 'frequency_5of_purchase']

In [18]:
['Customer ID', ' Age ', 'Gender']

['Customer ID', ' Age ', 'Gender']

In [19]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['customer_id', 'age_', 'gender', 'item_purchase', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subcription_status', 'ship[ping_type', 'discount_applied', '_promo_code_used', 'previous_purchase', 'payment_method', 'frequency_5of_purchase']

In [20]:
print(df.columns.tolist())

['customer_id', 'age_', 'gender', 'item_purchase', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subcription_status', 'ship[ping_type', 'discount_applied', '_promo_code_used', 'previous_purchase', 'payment_method', 'frequency_5of_purchase']

In [ ]:
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels=labels)

In [ ]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_5of_purchases'].mp(frequency_mapping)

In [25]:
print(df.columns.tolist())

['customer_id', 'age_', 'gender', 'item_purchase', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subcription_status', 'ship[ping_type', 'discount_applied', '_promo_code_used', 'previous_purchase', 'payment_method', 'frequency_5of_purchase']

In [26]:
'purchase_frequency_days'
'frequency_5of_purchases'

'frequency_5of_purchases'

In [27]:
df[['frequency_5of_purchase']].head(10)

  frequency_5of_purchase
0            Fortnightly
1            Fortnightly
2                 Weekly
3                 Weekly
4               Annually
5                 Weekly
6              Quarterly
7                 Weekly
8               Annually
9              Quarterly

In [29]:
labels = ['Young Adult', 'Adult', 'Middle_Aged', 'Senior']

df['age_group'] = pd.qcut(df['age_'], q=4, labels=labels)

df[['age_', 'age_group']].head(10)

   age_    age_group
0    55  Middle_Aged
1    19  Young Adult
2    50  Middle_Aged
3    21  Young Adult
4    45  Middle_Aged
5    46  Middle_Aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle_Aged

In [31]:
df = df.rename(columns={
    '_promo_code_used': 'promo_code_used'
})

In [32]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [33]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [34]:
df=df.drop('promo_code_used',axis=1)
df.columns

Index(['customer_id', 'age_', 'gender', 'item_purchase', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subcription_status', 'ship[ping_type',
       'discount_applied', 'previous_purchase', 'payment_method',
       'frequency_5of_purchase', 'age_group'],
      dtype='str')

In [36]:
pip install psycopg2.binary sqlalchemy

Requirement already satisfied: psycopg2.binary in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
database = "customer behaviour"

In [11]:
import pandas as pd
from sqlalchemy import create_engine

# Load data
df = pd.read_csv(r"C:\Users\Admin\OneDrive\Documents\Mrudula\Customer Shopping Behavior Analysis.csv")

# Database connection details
username = "postgres"
password = "pass12@3"
host = "localhost"
port = "5432"
database = "customer_behaviour"

# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Load data into PostgreSQL
table_name = "customer shopping"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}'")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (4038435636.py, line 5)

In [14]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [15]:
df = pd.read_csv(
    r"C:\Users\Admin\OneDrive\Documents\Mrudula\Customer Shopping Behavior Analysis.csv"
)

In [16]:
print(df.head())

  Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0  1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,W...
1  2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,W...
2  3,50,Male,Jeans,Clothing,73,Massachusetts,S,Ma...
3  4,21,Male,Sandals,Footwear,90,Rhode Island,M,M...
4  5,45,Male,Blouse,Clothing,49,Oregon,M,Turquois...

In [17]:
username = "postgres"
password = quote_plus("pass12@3")
host = "localhost"
port = "5432"
database = "customer_behaviour"

In [18]:
quote_plus("pass12@3")

'pass12%403'

In [19]:
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

In [21]:
username = "postgres"
password = "pass12@3"
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

In [22]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("pass12@3")
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

In [25]:
username = ?
password = ?
host = ?
port = ?
engine = create_engine(...)

SyntaxError: invalid syntax (856200666.py, line 1)

In [28]:
username = "postgres"
password = "pass123"
host = "localhost"
port = "5432"
database = "customer_behaviour"